#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Посылка запроса на получение дампов таблиц
"""

import argparse

from dumper import Dumper, DumperError

ADDRESS = 'urn:sm:gis@uprdor-rus'

if __name__ == '__main__':
    dumper = Dumper(config_name='/etc/pg_replica.conf')

    for table in dumper.tables:
        stored_dumps = dumper.get_file_list(table)
        if not stored_dumps:
            dumper.ask_for_dump(ADDRESS, table)