#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''Скрипт для создания и отправки дампов запрошенной таблицы.
'''

import argparse
import xml.etree.ElementTree as et

from dumper import Dumper, DumperError

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('query', help='query file')
    args = parser.parse_args()
    query_file = args.query

    tree = et.parse(query_file)
    root = tree.getroot()
    header = root.find('{http://schemas.xmlsoap.org/soap/envelope/}Header')
    sender = header.find('{http://www.w3.org/2005/08/addressing}From')
    peer = sender.find('{http://www.w3.org/2005/08/addressing}Address').text
    action = header.find('{http://www.w3.org/2005/08/addressing}Action').text
    body = root.find('{http://schemas.xmlsoap.org/soap/envelope/}Body')

    tablename = body.find('tbl').text

    dumper = Dumper(config_name='/etc/pg_replica.conf')

    # import ipdb
    # ipdb.set_trace()
    dumper.dump_table(peer, tablename)