#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Посылка запроса на получение дампов таблиц
"""

import argparse
import logging
import ConfigParser

from bus_communicator import BusCommunicator
from pgdb import *

ADDRESS = 'urn:sm:gis@rosavtodor'

logger = logging.getLogger('triggers-ask')


if __name__ == '__main__':

    logger.setLevel(logging.DEBUG)

    ch = logging.StreamHandler()
    ch.setLevel(logging.ERROR)

    formatter = logging.Formatter('%(asctime)s %(name)s: %(levelname)s: %(message)s', datefmt='%b %d %H:%M:%S')
    ch.setFormatter(formatter)

    logger.addHandler(ch)

    config_name = '/etc/pg_replica.conf'
    #config_name = 'pg_replica.conf'
    if not os.path.isfile(config_name):
        logger.critical('Configuration file "%s" not found.' % config_name)
        sys.exit(1)

    cfg = ConfigParser.SafeConfigParser({'log_file': '/var/log/pg_replica.log', 'log_level': 'debug'})

    cfg.read(config_name)
    log_file = cfg.get('logging', 'log_file')
    log_level = cfg.get('logging', 'log_level')


    if cfg.has_section('database'):
        host = cfg.get('database', 'host')
        port = cfg.getint('database', 'port')
        dbname = cfg.get('database', 'database')
        db_user = cfg.get('database', 'user')
        db_passwd = cfg.get('database', 'password')
        com_table = cfg.get('database', 'com_table')
        com_schema = cfg.get('database', 'com_schema')
    else:
        logger.critical('Invalid config file.')
        sys.exit(1)

    if cfg.has_section('bus'):
        uri = cfg.get('bus', 'uri')
        bus_user = cfg.get('bus', 'user')
        bus_passwd = cfg.get('bus', 'password')
        addr = cfg.get('bus', 'address')
    else:
        logger.critical('Invalid config file.')
        sys.exit(1)

    logger.debug('Get trigger list processing.')

    sender = BusCommunicator(uri,
                             addr,
                             bus_user,
                             bus_passwd)

    action = 'sm://messages/application/gis/geochanges_direction'
    request = 'triggersInfoRequest'
    sender.send_message(ADDRESS, request, action)

    logger.debug('Stop trigger list processing.')
    logger.info('Stop logging.')
