#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Посылка запроса на получение дампов таблиц
"""

import argparse
import logging
import ConfigParser
import xml.etree.ElementTree as et

from bus_communicator import BusCommunicator
from pgdb import *


logger = logging.getLogger('triggers-ask')


if __name__ == '__main__':

    logger.setLevel(logging.DEBUG)

    ch = logging.StreamHandler()
    ch.setLevel(logging.ERROR)

    formatter = logging.Formatter('%(asctime)s %(name)s: %(levelname)s: %(message)s', datefmt='%b %d %H:%M:%S')
    ch.setFormatter(formatter)

    logger.addHandler(ch)

    parser = argparse.ArgumentParser()
    parser.add_argument('trigger_request', help='trigger request')
    args = parser.parse_args()
    trigger_request = args.trigger_request

    config_name = '/etc/pg_replica.conf'
    #config_name = 'pg_replica.conf'
    if not os.path.isfile(config_name):
        logger.critical('Configuration file "%s" not found.' % config_name)
        sys.exit(1)

    cfg = ConfigParser.SafeConfigParser({'log_file': '/var/log/pg_replica.log', 'log_level': 'debug'})

    cfg.read(config_name)
    log_file = cfg.get('logging', 'log_file')
    log_level = cfg.get('logging', 'log_level')


    if cfg.has_section('database'):
        host = cfg.get('database', 'host')
        port = cfg.getint('database', 'port')
        dbname = cfg.get('database', 'database')
        db_user = cfg.get('database', 'user')
        db_passwd = cfg.get('database', 'password')
        com_table = cfg.get('database', 'com_table')
        com_schema = cfg.get('database', 'com_schema')
    else:
        logger.critical('Invalid config file.')
        sys.exit(1)

    if cfg.has_section('bus'):
        uri = cfg.get('bus', 'uri')
        bus_user = cfg.get('bus', 'user')
        bus_passwd = cfg.get('bus', 'password')
        addr = cfg.get('bus', 'address')
    else:
        logger.critical('Invalid config file.')
        sys.exit(1)

    if cfg.has_section('fulldump'):
        tables = cfg.get('fulldump', 'tables_for_dump')
        tables = [t.strip() for t in tables.split(',')]
    else:
        logger.critical('Invalid config file.')
        sys.exit(1)

    logger.debug('Start trigger info processing.')


    tree = et.parse(trigger_request)
    root = tree.getroot()
    header = root.find('{http://schemas.xmlsoap.org/soap/envelope/}Header')
    sender = header.find('{http://www.w3.org/2005/08/addressing}From')
    peer = sender.find('{http://www.w3.org/2005/08/addressing}Address').text
    action = header.find('{http://www.w3.org/2005/08/addressing}Action').text
    body = root.find('{http://schemas.xmlsoap.org/soap/envelope/}Body')

    trig_info = body.find('tbls').text

    db = PgDB(host, port, dbname, db_user, db_passwd)
    c = db.con.cursor()

    info = trig_info.split(',')

    for tabinfo in info:
        tab, status = tabinfo.split(':')
        if not db.is_trigger_exist(tab):
            logger.error('Trigger for table %s does not exist.' % tab)
        else:
            if status == 'enabled':
                db.disable_trigger(tab)
            else:
                db.enable_trigger(tab)
            new_status = 'disabled' if  db.is_trigger_disabled(tab) else 'enabled'
            logger.info('Status of trigger for table %s is %s now.' %
                        (tab, new_status))

    logger.debug('Stop trigger toggle processing.')
    logger.info('Stop logging.')
